### PR TITLE
Allow setting styles on date cell

### PR DESCRIPTION
**Pull request by jordanwallwork**
Added a simple option to allow specifying cell styles

### CODE REVIEW

**Comment by GramThanos** [comment]
Why not just use CSS to do so?

```css
.jsCalendar tbody td:nth-child(1), .jsCalendar tbody td:nth-child(7) {
    font-weight: bold;
}
```
or if you have Monday first

```css
.jsCalendar tbody td:nth-child(6), .jsCalendar tbody td:nth-child(7) {
    font-weight: bold;
}
```

In order to allow UI tweaks through Javascript, I am considering implementing an extension system for version 2 to allow pre-render and post-render modifications.

**Comment by jordanwallwork** [comment]
I just used making dates bold as an example to show how it's used. I'm using it alongside a backing event store to indicate things happening on certain dates. My code looks more like:

    getCellStyle: function (date) {
        var summary = eventStore.getEventSummaryForDate(date);
        if (summary.hasImportant) return "font-weight:bold;color:#f00";
        else if (summary.events.count > 1) return "font-weight:bold";
    }

**Comment by GramThanos** [comment]
Ok, now I get it. But I feel like `getCellStyle` is too specific.

I  think I am going to merge this and convert it to something like 
```javascript
function onDateRender(date, cell) {
    // We will also give access to `this` as the jsCalendar instance

    var summary = eventStore.getEventSummaryForDate(date);
    if (summary.hasImportant) {
        cell.style.fontWeight = 'bold';
        cell.style.color= '#f00';
    }
    else if (summary.events.count > 1) {
        cell.style.fontWeight = 'bold';
    }

    // We will be able to alter the contents too, maybe add the number of events
    if (summary.events.count > 0) {
        let span = document.createElement('span');
        span.className = 'date-events';
        span.textContent = summary.events.count;
        cell.appendChild(span);
    }
}
```
So that it can cover more applications.

What do you think?

**Comment by jordanwallwork** [comment]
Yeah that makes total sense. That's actually what I started with and then I made it more specific to fit my requirements, I hadn't anticipated submitting a PR but then decided I may as well in case someone else found it useful

**Pull request merged**
