### PR TITLE
Added two languages

### PR DESCRIPTION
**Pull request by anstapol**
Provides support to the next languages:
- Ukrainian
- Catalan

### CODE REVIEW

**Comment by GramThanos** [comment]
Thanks for the translations!

I think that the Ukrainian language code is `uk` (we use the [ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)). Can you change it?

**Comment by anstapol** [comment]
Yes sure give me a sec

**Comment by GramThanos** [comment]
I just now realized that we already had `uk` language :laughing:

**Comment by anstapol** [comment]
Yeah, I thought it was English from United Kingdom 😅
Didn't realised the language code specification at first place

**Pull request closed without merging**
