### PR TITLE
Arabic support language

### PR DESCRIPTION
**Pull request by JefferyHus**

### CODE REVIEW

**Comment by JefferyHus** [comment]
This pull request must not be merged yet, unless #48 has been merged.

**Comment by GramThanos** [comment]
This PR needs cleanup :P
I think you will have to fork the project again and commit only the Arabic language.

**Comment by JefferyHus** [comment]
Yeah I tried twice and that damn old commit still there, I just set it as drat and waiting for a decision for the other PR then I can fix this one :D

**Comment by GramThanos** [comment]
Right now I am interested in the language only :P

**Comment by JefferyHus** [comment]
Done.

**Comment by GramThanos** [comment]
I have some questions!
Since I don't know how Arabic works, do you have abbreviation when showing the days?

Example 

| Type | Arabic | English |
| ------------- | ------------- | ------------- |
| 1-char abbreviation | ?, ?, ?, ?, ?, ?, ? | S, M, T, W, T, F, S |
| 2-char abbreviation | ??, ??, ??, ??, ??, ??, ?? | Su, Mo, Tu, We, Th, Fr, Sa |

**Comment by JefferyHus** [comment]
Unfortunately we don't have abbreviations like that in Arabic

**Comment by GramThanos** [comment]
So I guess this makes no sense

image

I will leave the example with full names
image

**Comment by GramThanos** [comment]
😃 Good job!

**Pull request merged**
